<?php

return [
    'hero-centered' => [
        'category' => 'shared',
        'block_name' => 'Element — Hero Centered',
        'description' => 'Reusable Hero element for blueprints, sections, and landing pages.',
        'block_type' => 'Hero',
        'view' => 'blocks.shared.hero-centered',
    ],
    'hero-split' => [
        'category' => 'shared',
        'block_name' => 'Element — Hero Split',
        'description' => 'Reusable Hero element for blueprints, sections, and landing pages.',
        'block_type' => 'Hero',
        'view' => 'blocks.shared.hero-split',
    ],
    'hero-video' => [
        'category' => 'shared',
        'block_name' => 'Element — Hero Video',
        'description' => 'Reusable Hero element for blueprints, sections, and landing pages.',
        'block_type' => 'Hero',
        'view' => 'blocks.shared.hero-video',
    ],
    'hero-healthcare' => [
        'category' => 'shared',
        'block_name' => 'Element — Hero Healthcare',
        'description' => 'Reusable Hero element for blueprints, sections, and landing pages.',
        'block_type' => 'Hero',
        'view' => 'blocks.shared.hero-healthcare',
    ],
    'cta-simple' => [
        'category' => 'shared',
        'block_name' => 'Element — Cta Simple',
        'description' => 'Reusable CTA element for blueprints, sections, and landing pages.',
        'block_type' => 'CTA',
        'view' => 'blocks.shared.cta-simple',
    ],
    'cta-split' => [
        'category' => 'shared',
        'block_name' => 'Element — Cta Split',
        'description' => 'Reusable CTA element for blueprints, sections, and landing pages.',
        'block_type' => 'CTA',
        'view' => 'blocks.shared.cta-split',
    ],
    'cta-banner' => [
        'category' => 'shared',
        'block_name' => 'Element — Cta Banner',
        'description' => 'Reusable CTA element for blueprints, sections, and landing pages.',
        'block_type' => 'CTA',
        'view' => 'blocks.shared.cta-banner',
    ],
    'cta-sticky' => [
        'category' => 'shared',
        'block_name' => 'Element — Cta Sticky',
        'description' => 'Reusable CTA element for blueprints, sections, and landing pages.',
        'block_type' => 'CTA',
        'view' => 'blocks.shared.cta-sticky',
    ],
    'features-grid' => [
        'category' => 'shared',
        'block_name' => 'Element — Features Grid',
        'description' => 'Reusable Features element for blueprints, sections, and landing pages.',
        'block_type' => 'Features',
        'view' => 'blocks.shared.features-grid',
    ],
    'features-icons' => [
        'category' => 'shared',
        'block_name' => 'Element — Features Icons',
        'description' => 'Reusable Features element for blueprints, sections, and landing pages.',
        'block_type' => 'Features',
        'view' => 'blocks.shared.features-icons',
    ],
    'services-benefits' => [
        'category' => 'shared',
        'block_name' => 'Element — Services Benefits',
        'description' => 'Reusable Features element for blueprints, sections, and landing pages.',
        'block_type' => 'Features',
        'view' => 'blocks.shared.services-benefits',
    ],
    'statistics-row' => [
        'category' => 'shared',
        'block_name' => 'Element — Statistics Row',
        'description' => 'Reusable Statistics element for blueprints, sections, and landing pages.',
        'block_type' => 'Statistics',
        'view' => 'blocks.shared.statistics-row',
    ],
    'statistics-cards' => [
        'category' => 'shared',
        'block_name' => 'Element — Statistics Cards',
        'description' => 'Reusable Statistics element for blueprints, sections, and landing pages.',
        'block_type' => 'Statistics',
        'view' => 'blocks.shared.statistics-cards',
    ],
    'process-steps' => [
        'category' => 'shared',
        'block_name' => 'Element — Process Steps',
        'description' => 'Reusable Process element for blueprints, sections, and landing pages.',
        'block_type' => 'Process',
        'view' => 'blocks.shared.process-steps',
    ],
    'process-flow' => [
        'category' => 'shared',
        'block_name' => 'Element — Process Flow',
        'description' => 'Reusable Process element for blueprints, sections, and landing pages.',
        'block_type' => 'Process',
        'view' => 'blocks.shared.process-flow',
    ],
    'testimonials-carousel' => [
        'category' => 'shared',
        'block_name' => 'Element — Testimonials Carousel',
        'description' => 'Reusable Testimonials element for blueprints, sections, and landing pages.',
        'block_type' => 'Testimonials',
        'view' => 'blocks.shared.testimonials-carousel',
    ],
    'testimonials-grid' => [
        'category' => 'shared',
        'block_name' => 'Element — Testimonials Grid',
        'description' => 'Reusable Testimonials element for blueprints, sections, and landing pages.',
        'block_type' => 'Testimonials',
        'view' => 'blocks.shared.testimonials-grid',
    ],
    'testimonials-highlight' => [
        'category' => 'shared',
        'block_name' => 'Element — Testimonials Highlight',
        'description' => 'Reusable Testimonials element for blueprints, sections, and landing pages.',
        'block_type' => 'Testimonials',
        'view' => 'blocks.shared.testimonials-highlight',
    ],
    'reviews-grid' => [
        'category' => 'shared',
        'block_name' => 'Element — Reviews Grid',
        'description' => 'Reusable Reviews element for blueprints, sections, and landing pages.',
        'block_type' => 'Reviews',
        'view' => 'blocks.shared.reviews-grid',
    ],
    'reviews-bar' => [
        'category' => 'shared',
        'block_name' => 'Element — Reviews Bar',
        'description' => 'Reusable Reviews element for blueprints, sections, and landing pages.',
        'block_type' => 'Reviews',
        'view' => 'blocks.shared.reviews-bar',
    ],
    'faq-accordion' => [
        'category' => 'shared',
        'block_name' => 'Element — Faq Accordion',
        'description' => 'Reusable FAQ element for blueprints, sections, and landing pages.',
        'block_type' => 'FAQ',
        'view' => 'blocks.shared.faq-accordion',
    ],
    'faq-columns' => [
        'category' => 'shared',
        'block_name' => 'Element — Faq Columns',
        'description' => 'Reusable FAQ element for blueprints, sections, and landing pages.',
        'block_type' => 'FAQ',
        'view' => 'blocks.shared.faq-columns',
    ],
    'team-grid' => [
        'category' => 'shared',
        'block_name' => 'Element — Team Grid',
        'description' => 'Reusable Team element for blueprints, sections, and landing pages.',
        'block_type' => 'Team',
        'view' => 'blocks.shared.team-grid',
    ],
    'team-leaders' => [
        'category' => 'shared',
        'block_name' => 'Element — Team Leaders',
        'description' => 'Reusable Team element for blueprints, sections, and landing pages.',
        'block_type' => 'Team',
        'view' => 'blocks.shared.team-leaders',
    ],
    'gallery-grid' => [
        'category' => 'shared',
        'block_name' => 'Element — Gallery Grid',
        'description' => 'Reusable Gallery element for blueprints, sections, and landing pages.',
        'block_type' => 'Gallery',
        'view' => 'blocks.shared.gallery-grid',
    ],
    'gallery-showcase' => [
        'category' => 'shared',
        'block_name' => 'Element — Gallery Showcase',
        'description' => 'Reusable Gallery element for blueprints, sections, and landing pages.',
        'block_type' => 'Gallery',
        'view' => 'blocks.shared.gallery-showcase',
    ],
    'before-after' => [
        'category' => 'shared',
        'block_name' => 'Element — Before After',
        'description' => 'Reusable Gallery element for blueprints, sections, and landing pages.',
        'block_type' => 'Gallery',
        'view' => 'blocks.shared.before-after',
    ],
    'video-embed' => [
        'category' => 'shared',
        'block_name' => 'Element — Video Embed',
        'description' => 'Reusable Video element for blueprints, sections, and landing pages.',
        'block_type' => 'Video',
        'view' => 'blocks.shared.video-embed',
    ],
    'video-sidecar' => [
        'category' => 'shared',
        'block_name' => 'Element — Video Sidecar',
        'description' => 'Reusable Video element for blueprints, sections, and landing pages.',
        'block_type' => 'Video',
        'view' => 'blocks.shared.video-sidecar',
    ],
    'contact-split' => [
        'category' => 'shared',
        'block_name' => 'Element — Contact Split',
        'description' => 'Reusable Contact element for blueprints, sections, and landing pages.',
        'block_type' => 'Contact',
        'view' => 'blocks.shared.contact-split',
    ],
    'form-callback' => [
        'category' => 'shared',
        'block_name' => 'Element — Form Callback',
        'description' => 'Reusable Forms element for blueprints, sections, and landing pages.',
        'block_type' => 'Forms',
        'view' => 'blocks.shared.form-callback',
    ],
    'form-newsletter' => [
        'category' => 'shared',
        'block_name' => 'Element — Form Newsletter',
        'description' => 'Reusable Forms element for blueprints, sections, and landing pages.',
        'block_type' => 'Forms',
        'view' => 'blocks.shared.form-newsletter',
    ],
    'pricing-tiers' => [
        'category' => 'shared',
        'block_name' => 'Element — Pricing Tiers',
        'description' => 'Reusable Pricing element for blueprints, sections, and landing pages.',
        'block_type' => 'Pricing',
        'view' => 'blocks.shared.pricing-tiers',
    ],
    'pricing-table' => [
        'category' => 'shared',
        'block_name' => 'Element — Pricing Table',
        'description' => 'Reusable Pricing element for blueprints, sections, and landing pages.',
        'block_type' => 'Pricing',
        'view' => 'blocks.shared.pricing-table',
    ],
    'comparison-features' => [
        'category' => 'shared',
        'block_name' => 'Element — Comparison Features',
        'description' => 'Reusable Comparison element for blueprints, sections, and landing pages.',
        'block_type' => 'Comparison',
        'view' => 'blocks.shared.comparison-features',
    ],
    'trust-bar-icons' => [
        'category' => 'shared',
        'block_name' => 'Element — Trust Bar Icons',
        'description' => 'Reusable Trust Bar element for blueprints, sections, and landing pages.',
        'block_type' => 'Trust Bar',
        'view' => 'blocks.shared.trust-bar-icons',
    ],
    'trust-bar-badges' => [
        'category' => 'shared',
        'block_name' => 'Element — Trust Bar Badges',
        'description' => 'Reusable Trust Bar element for blueprints, sections, and landing pages.',
        'block_type' => 'Trust Bar',
        'view' => 'blocks.shared.trust-bar-badges',
    ],
    'logos-partners' => [
        'category' => 'shared',
        'block_name' => 'Element — Logos Partners',
        'description' => 'Reusable Logos element for blueprints, sections, and landing pages.',
        'block_type' => 'Logos',
        'view' => 'blocks.shared.logos-partners',
    ],
    'location-radius' => [
        'category' => 'shared',
        'block_name' => 'Element — Location Radius',
        'description' => 'Reusable Sections element for blueprints, sections, and landing pages.',
        'block_type' => 'Sections',
        'view' => 'blocks.shared.location-radius',
    ],
    'timeline-milestones' => [
        'category' => 'shared',
        'block_name' => 'Element — Timeline Milestones',
        'description' => 'Reusable Timeline element for blueprints, sections, and landing pages.',
        'block_type' => 'Timeline',
        'view' => 'blocks.shared.timeline-milestones',
    ],
    'cards-icon-row' => [
        'category' => 'shared',
        'block_name' => 'Element — Cards Icon Row',
        'description' => 'Reusable Cards element for blueprints, sections, and landing pages.',
        'block_type' => 'Cards',
        'view' => 'blocks.shared.cards-icon-row',
    ],
    'cards-image-row' => [
        'category' => 'shared',
        'block_name' => 'Element — Cards Image Row',
        'description' => 'Reusable Cards element for blueprints, sections, and landing pages.',
        'block_type' => 'Cards',
        'view' => 'blocks.shared.cards-image-row',
    ],
    'content-prose' => [
        'category' => 'shared',
        'block_name' => 'Element — Content Prose',
        'description' => 'Reusable Text element for blueprints, sections, and landing pages.',
        'block_type' => 'Text',
        'view' => 'blocks.shared.content-prose',
    ],
    'content-split' => [
        'category' => 'shared',
        'block_name' => 'Element — Content Split',
        'description' => 'Reusable Text element for blueprints, sections, and landing pages.',
        'block_type' => 'Text',
        'view' => 'blocks.shared.content-split',
    ],
    'callout-tip' => [
        'category' => 'shared',
        'block_name' => 'Element — Callout Tip',
        'description' => 'Reusable Callout element for blueprints, sections, and landing pages.',
        'block_type' => 'Callout',
        'view' => 'blocks.shared.callout-tip',
    ],
    'callout-highlight' => [
        'category' => 'shared',
        'block_name' => 'Element — Callout Highlight',
        'description' => 'Reusable Callout element for blueprints, sections, and landing pages.',
        'block_type' => 'Callout',
        'view' => 'blocks.shared.callout-highlight',
    ],
    'lead-magnet-guide' => [
        'category' => 'shared',
        'block_name' => 'Element — Lead Magnet Guide',
        'description' => 'Reusable Lead Magnet element for blueprints, sections, and landing pages.',
        'block_type' => 'Lead Magnet',
        'view' => 'blocks.shared.lead-magnet-guide',
    ],
    'lead-magnet-webinar' => [
        'category' => 'shared',
        'block_name' => 'Element — Lead Magnet Webinar',
        'description' => 'Reusable Lead Magnet element for blueprints, sections, and landing pages.',
        'block_type' => 'Lead Magnet',
        'view' => 'blocks.shared.lead-magnet-webinar',
    ],
];
