<?php

/**
 * Global Style Packs — assign block/header/carousel/button variants site-wide.
 * Consumed by StylePackRegistry; applied via ContentRenderContext on public render.
 */
return [

    'healthcare career consultancy_professional' => [
        'label' => 'Healthcare Career Professional',
        'visual_language' => 'modern',
        'theme_preset_slug' => 'clinical_blue',
        'header_preset' => 'classic_healthcare career consultancy',
        'layout_preset' => 'contained',
        'assignments' => [
            'hero' => 'style_1',
            'services' => 'style_1',
            'cta' => 'style_1',
            'testimonials' => 'style_1',
            'faq' => 'style_1',
            'gallery' => 'style_1',
            'team' => 'style_1',
            'statistics' => 'style_1',
            'blog' => 'style_1',
            'footer' => 'style_1',
            'carousel' => 'style_1',
            'card' => 'style_1',
            'button' => 'style_1',
        ],
    ],

    'healthcare career consultancy_premium' => [
        'label' => 'Healthcare Career Premium',
        'visual_language' => 'premium',
        'theme_preset_slug' => 'premium_gold',
        'header_preset' => 'premium',
        'layout_preset' => 'contained',
        'assignments' => [
            'hero' => 'style_2',
            'services' => 'style_2',
            'cta' => 'style_2',
            'testimonials' => 'style_2',
            'faq' => 'style_2',
            'gallery' => 'style_2',
            'team' => 'style_2',
            'statistics' => 'style_2',
            'blog' => 'style_2',
            'footer' => 'style_2',
            'carousel' => 'style_2',
            'card' => 'style_2',
            'button' => 'style_2',
        ],
    ],

    'healthcare career consultancy_modern' => [
        'label' => 'Healthcare Career Modern',
        'visual_language' => 'modern',
        'theme_preset_slug' => 'modern_purple',
        'header_preset' => 'modern',
        'layout_preset' => 'wide',
        'assignments' => [
            'hero' => 'style_3',
            'services' => 'style_3',
            'cta' => 'style_3',
            'testimonials' => 'style_3',
            'faq' => 'style_3',
            'gallery' => 'style_3',
            'team' => 'style_3',
            'statistics' => 'style_3',
            'blog' => 'style_3',
            'footer' => 'style_3',
            'carousel' => 'style_3',
            'card' => 'style_3',
            'button' => 'style_3',
        ],
    ],

    'construction_industrial' => [
        'label' => 'Construction Industrial',
        'visual_language' => 'corporate',
        'theme_preset_slug' => 'forest_green',
        'header_preset' => 'corporate',
        'layout_preset' => 'wide',
        'assignments' => [
            'hero' => 'style_1',
            'services' => 'style_4',
            'cta' => 'style_1',
            'testimonials' => 'style_1',
            'faq' => 'style_1',
            'gallery' => 'style_2',
            'team' => 'style_1',
            'statistics' => 'style_2',
            'blog' => 'style_1',
            'footer' => 'style_1',
            'carousel' => 'style_2',
            'card' => 'style_2',
            'button' => 'style_1',
        ],
    ],

    'construction_premium' => [
        'label' => 'Construction Premium',
        'visual_language' => 'premium',
        'theme_preset_slug' => 'luxury_black',
        'header_preset' => 'premium',
        'layout_preset' => 'contained',
        'assignments' => [
            'hero' => 'style_2',
            'services' => 'style_2',
            'cta' => 'style_2',
            'testimonials' => 'style_2',
            'faq' => 'style_2',
            'gallery' => 'style_3',
            'team' => 'style_2',
            'statistics' => 'style_3',
            'blog' => 'style_2',
            'footer' => 'style_2',
            'carousel' => 'style_3',
            'card' => 'style_3',
            'button' => 'style_2',
        ],
    ],

    'education_clean' => [
        'label' => 'Education Clean',
        'visual_language' => 'minimal',
        'theme_preset_slug' => 'clinical_blue',
        'header_preset' => 'minimal',
        'layout_preset' => 'contained',
        'assignments' => [
            'hero' => 'style_3',
            'services' => 'style_1',
            'cta' => 'style_3',
            'testimonials' => 'style_1',
            'faq' => 'style_2',
            'gallery' => 'style_1',
            'team' => 'style_1',
            'statistics' => 'style_1',
            'blog' => 'style_2',
            'footer' => 'style_1',
            'carousel' => 'style_1',
            'card' => 'style_1',
            'button' => 'style_3',
        ],
    ],

    'consultancy_corporate' => [
        'label' => 'Consultancy Corporate',
        'visual_language' => 'corporate',
        'theme_preset_slug' => 'clinical_blue',
        'header_preset' => 'corporate',
        'layout_preset' => 'contained',
        'assignments' => [
            'hero' => 'style_4',
            'services' => 'style_3',
            'cta' => 'style_4',
            'testimonials' => 'style_3',
            'faq' => 'style_3',
            'gallery' => 'style_2',
            'team' => 'style_3',
            'statistics' => 'style_2',
            'blog' => 'style_3',
            'footer' => 'style_2',
            'carousel' => 'style_2',
            'card' => 'style_2',
            'button' => 'style_4',
        ],
    ],

    'luxury_black' => [
        'label' => 'Luxury Black',
        'visual_language' => 'luxury',
        'theme_preset_slug' => 'luxury_black',
        'header_preset' => 'premium',
        'layout_preset' => 'contained',
        'assignments' => [
            'hero' => 'style_5',
            'services' => 'style_5',
            'cta' => 'style_5',
            'testimonials' => 'style_5',
            'faq' => 'style_4',
            'gallery' => 'style_4',
            'team' => 'style_4',
            'statistics' => 'style_4',
            'blog' => 'style_4',
            'footer' => 'style_5',
            'carousel' => 'style_4',
            'card' => 'style_5',
            'button' => 'style_5',
        ],
    ],

    'minimal_white' => [
        'label' => 'Minimal White',
        'visual_language' => 'minimal',
        'theme_preset_slug' => 'clinical_blue',
        'header_preset' => 'minimal',
        'layout_preset' => 'contained',
        'assignments' => [
            'hero' => 'style_1',
            'services' => 'style_1',
            'cta' => 'style_1',
            'testimonials' => 'style_1',
            'faq' => 'style_1',
            'gallery' => 'style_1',
            'team' => 'style_1',
            'statistics' => 'style_1',
            'blog' => 'style_1',
            'footer' => 'style_1',
            'carousel' => 'style_1',
            'card' => 'style_1',
            'button' => 'style_1',
        ],
    ],

    'modern_purple' => [
        'label' => 'Modern Purple',
        'visual_language' => 'modern',
        'theme_preset_slug' => 'modern_purple',
        'header_preset' => 'modern',
        'layout_preset' => 'wide',
        'assignments' => [
            'hero' => 'style_3',
            'services' => 'style_3',
            'cta' => 'style_3',
            'testimonials' => 'style_3',
            'faq' => 'style_3',
            'gallery' => 'style_3',
            'team' => 'style_3',
            'statistics' => 'style_3',
            'blog' => 'style_3',
            'footer' => 'style_3',
            'carousel' => 'style_3',
            'card' => 'style_3',
            'button' => 'style_3',
        ],
    ],

];
