<?php

/**
 * Built-in public theme presets (Phase 8).
 * Seeded into theme_presets; cloned/customized via Appearance settings.
 */
return [

    'clinical_blue' => [
        'name' => 'Clinical Blue',
        'shell' => 'public',
        'header_preset' => 'classic_digital growth platform',
        'layout_preset' => 'contained',
        'tokens' => [
            'primary' => '#0055ff',
            'primary_hover' => '#001e5c',
            'navy' => '#001f5c',
            'navy_mid' => '#012a7d',
            'navy_border' => '#001433',
            'navy_accent' => '#164081',
            'text_primary' => '#0f172a',
            'text_secondary' => '#475569',
            'text_muted' => '#64748b',
            'surface' => '#ffffff',
            'surface_muted' => '#f8fafc',
            'border' => '#e2e8f0',
            'success' => '#16a34a',
            'warning' => '#d97706',
            'danger' => '#dc2626',
        ],
        'typography' => [
            'heading_font' => 'Plus Jakarta Sans',
            'body_font' => 'Plus Jakarta Sans',
            'scale' => 'default',
        ],
    ],

    'premium_gold' => [
        'name' => 'Premium Gold',
        'shell' => 'public',
        'header_preset' => 'premium',
        'layout_preset' => 'contained',
        'tokens' => [
            'primary' => '#c5a059',
            'primary_hover' => '#a88748',
            'navy' => '#120f0d',
            'navy_mid' => '#1a1614',
            'navy_border' => '#3d342d',
            'navy_accent' => '#c5a059',
            'text_primary' => '#0f172a',
            'text_secondary' => '#475569',
            'text_muted' => '#64748b',
            'surface' => '#ffffff',
            'surface_muted' => '#faf8f5',
            'border' => '#e7e0d4',
            'success' => '#16a34a',
            'warning' => '#d97706',
            'danger' => '#dc2626',
        ],
        'typography' => [
            'heading_font' => 'Plus Jakarta Sans',
            'body_font' => 'Noto Sans',
            'scale' => 'default',
        ],
    ],

    'forest_green' => [
        'name' => 'Forest Green',
        'shell' => 'public',
        'header_preset' => 'corporate',
        'layout_preset' => 'wide',
        'tokens' => [
            'primary' => '#15803d',
            'primary_hover' => '#166534',
            'navy' => '#14532d',
            'navy_mid' => '#166534',
            'navy_border' => '#052e16',
            'navy_accent' => '#22c55e',
            'text_primary' => '#0f172a',
            'text_secondary' => '#475569',
            'text_muted' => '#64748b',
            'surface' => '#ffffff',
            'surface_muted' => '#f0fdf4',
            'border' => '#bbf7d0',
            'success' => '#16a34a',
            'warning' => '#d97706',
            'danger' => '#dc2626',
        ],
        'typography' => [
            'heading_font' => 'Plus Jakarta Sans',
            'body_font' => 'Plus Jakarta Sans',
            'scale' => 'default',
        ],
    ],

    'luxury_black' => [
        'name' => 'Luxury Black',
        'shell' => 'public',
        'header_preset' => 'premium',
        'layout_preset' => 'contained',
        'tokens' => [
            'primary' => '#f5f5f5',
            'primary_hover' => '#d4d4d4',
            'navy' => '#0a0a0a',
            'navy_mid' => '#171717',
            'navy_border' => '#262626',
            'navy_accent' => '#a3a3a3',
            'text_primary' => '#0f172a',
            'text_secondary' => '#525252',
            'text_muted' => '#737373',
            'surface' => '#ffffff',
            'surface_muted' => '#fafafa',
            'border' => '#e5e5e5',
            'success' => '#16a34a',
            'warning' => '#d97706',
            'danger' => '#dc2626',
        ],
        'typography' => [
            'heading_font' => 'Plus Jakarta Sans',
            'body_font' => 'Noto Sans',
            'scale' => 'default',
        ],
    ],

    'modern_purple' => [
        'name' => 'Modern Purple',
        'shell' => 'public',
        'header_preset' => 'modern',
        'layout_preset' => 'wide',
        'tokens' => [
            'primary' => '#7c3aed',
            'primary_hover' => '#5b21b6',
            'navy' => '#581c87',
            'navy_mid' => '#6b21a8',
            'navy_border' => '#3b0764',
            'navy_accent' => '#a855f7',
            'text_primary' => '#0f172a',
            'text_secondary' => '#475569',
            'text_muted' => '#64748b',
            'surface' => '#ffffff',
            'surface_muted' => '#faf5ff',
            'border' => '#e9d5ff',
            'success' => '#16a34a',
            'warning' => '#d97706',
            'danger' => '#dc2626',
        ],
        'typography' => [
            'heading_font' => 'Plus Jakarta Sans',
            'body_font' => 'Plus Jakarta Sans',
            'scale' => 'default',
        ],
    ],

];
